name: remote ssh command
on: [push, workflow_dispatch]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.API_SFTP_HOST }}
          username: ${{ secrets.API_SFTP_USERNAME }}
          password: ${{ secrets.API_SFTP_PASSWORD }}
          key: ${{ secrets.API_CPANEL_SSH_PRIVATE_KEY }}
          port: 21
          script: whoami
