name: remote ssh command
on: [push, workflow_dispatch]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.API_SSH_HOST }}
          username: ${{ secrets.API_SSH_USERNAME }}
          key: ${{ secrets.API_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.API_SSH_PASSPHRASE }}
          port: ${{ secrets.API_SSH_PORT }} # 21098 for NameCheap cName
          script: whoami
