#name: remote ssh command
#on: [push, workflow_dispatch]
#jobs:
#
#  build:
#    name: Build
#    runs-on: ubuntu-latest
#    steps:
#      - name: executing remote ssh commands using password
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.API_SSH_HOST }}
#          username: ${{ secrets.API_SSH_USERNAME }}
#          key: ${{ secrets.API_SSH_PRIVATE_KEY }}
#          passphrase: ${{ secrets.API_SSH_PASSPHRASE }}
#          port: ${{ secrets.API_SSH_PORT }} # 21098 for NameCheap cName
#          script: |
#            echo "Deployment started ..."
#
#            echo "which composer:"
#            which composer
#            composer --version
#
#            echo "--------"
#
#            echo "which php:"
#            which php
#            php -v
#
#            echo "--------"
#
#            cd asset-management-api.ibrahimsari.com.tr
#
#            echo "pwd:"
#            cd pwd
#
#            #### Enter maintenance mode or return true
#            #### if already is in maintenance mode
#            (php artisan down) || true
#
#            #### Install composer dependencies
#            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
#
#            #### Clear the old cache
#            php artisan clear-compiled
#
#            #### Recreate cache
#            php artisan optimize
#
#            #### Run database migrations
#            php artisan migrate --force --seed
#
#            ###php artisan migrate --force --seed
#            php artisan migrate:fresh --seed
#
#            #### php artisan storage:link
#
#            php artisan config:clear
#            php artisan config:cache
#
#            php artisan view:clear
#            php artisan route:cache
